<?php

namespace common\modules\disk\controllers;

use alexantr\elfinder\ConnectorAction;
use Leonied7\Yandex\Disk;
use Yii;
use yii\web\Controller;

class IndexController extends Controller
{

    public $yandexDisk ;

    public $layout = '@backend/themes/adminlte/views/layouts/common';

    public function init()
    {
        //crypto.parrot@yandex.ru
        $this->yandexDisk = new Disk('AQAAAABZPZGyAAdtkbk0aV5ZnEiQjJWtResyJHg');

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index',['yandexDisk'=>$this->yandexDisk]);
    }
}
